#!/usr/bin/env node

/**
 * This script generates a TypeScript file containing color variables
 * extracted from a global CSS file. It reads the CSS file, extracts
 * HSL color variables defined in @variant light/@variant dark blocks,
 * and writes them to a TypeScript file in a structured format.
 */

const fs = require("fs");
const path = require("path");

// Paths
// eslint-disable-next-line no-undef
const globalCssPath = path.join(__dirname, "../global.css");
// eslint-disable-next-line no-undef
const colorsTsPath = path.join(__dirname, "../constants/colors.ts");

// Read global.css
if (!fs.existsSync(globalCssPath)) {
	console.error("Error: global.css file not found.");
	process.exit(1);
}

const cssContent = fs.readFileSync(globalCssPath, "utf-8");

// Extract HSL variables from @variant light/@variant dark blocks
const rootRegex = /:root\s*{([^}]*)}/;
const darkRootRegex = /\.dark:root\s*{([^}]*)}/;

const extractVariantBlock = (css, variant) => {
	const marker = `@variant ${variant}`;
	const markerIndex = css.indexOf(marker);
	if (markerIndex === -1) return null;

	const braceStart = css.indexOf("{", markerIndex);
	if (braceStart === -1) return null;

	let depth = 0;
	for (let i = braceStart; i < css.length; i += 1) {
		const char = css[i];
		if (char === "{") depth += 1;
		if (char === "}") depth -= 1;
		if (depth === 0) {
			return css.slice(braceStart + 1, i);
		}
	}

	return null;
};

// Helper function to convert kebab-case to camelCase
const toCamelCase = (str) =>
	str.replace(/-([a-z])/g, (_, char) => char.toUpperCase());

const extractColors = (cssBlock) => {
	const hslRegex = /--([\w-]+):\s*([\d.]+)\s+([\d.]+)%\s+([\d.]+)%;/g;
	const colors = {};
	let match;

	while ((match = hslRegex.exec(cssBlock)) !== null) {
		// eslint-disable-next-line no-unused-vars
		const [_, name, h, s, l] = match;
		colors[toCamelCase(name)] = `hsl(${h}, ${s}%, ${l}%)`;
	}

	return colors;
};

const lightVariantBlock = extractVariantBlock(cssContent, "light");
const darkVariantBlock = extractVariantBlock(cssContent, "dark");

const rootMatch = rootRegex.exec(cssContent);
const darkRootMatch = darkRootRegex.exec(cssContent);

const rootColors = lightVariantBlock
	? extractColors(lightVariantBlock)
	: rootMatch
		? extractColors(rootMatch[1])
		: {};
const darkRootColors = darkVariantBlock
	? extractColors(darkVariantBlock)
	: darkRootMatch
		? extractColors(darkRootMatch[1])
		: {};

// Combine colors into a single object
const colors = {
	light: rootColors,
	dark: darkRootColors,
};

// Generate colors.ts content
const colorsTsContent = `/**
 * This file is auto-generated by the generate-colors.js script.
 * Do not edit this file directly.
 */

export const colors = ${JSON.stringify(colors, null, 2)};
`;

// Write to colors.ts
fs.writeFileSync(colorsTsPath, colorsTsContent, "utf-8");
console.log(`✅ colors.ts has been generated at ${colorsTsPath}`);
